meta_title: "People of Gaïa - Act for a better tomorrow"
meta_description: "Where will and need for action meet"
meta_image: "Mother-Nature.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@pog_twitter_account"